# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passenger.Passenger_profile')),
            ],
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('driver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver_profile')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.TripPlan'),
        ),
    ]
